from graph_models.micrograph import * 
from graph_models.tree_gen import * 
from graph_models.analog_schemes_aux import connect_subgraphs__prior_to_current 
from graph_models.shortest_paths import * 
from .pt_aux import *  
from morebs2.graph_basics import * 

"""
for a forest generated by a <TreeGen> instance, connects 
all the forest components. Uses measure 
    (ratio of prior subgraph nodes, ratio of possible edges to current subgraph) 
"""
def connect_TreeGen_forest(T:TreeGen,prg,sg2sg_conn_ratios=(0.15,0.1)): 
    gd = GraphComponentDecomposition(T.d)
    gd.decompose() 

    M = MicroGraph(T.d) 

    if len(gd.components) < 2: 
        return M.dg 

    c0,c1 = gd.components[0],gd.components[1]
    M0,M1 = M.subgraph_by_nodeset_(c0),M.subgraph_by_nodeset_(c1) 

    MX = [] 
    for i in range(len(gd.components) - 1): 
        c0,c1 = gd.components[i],gd.components[i+1] 
        M0,M1 = M.subgraph_by_nodeset_(c0),M.subgraph_by_nodeset_(c1) 

        G = connect_subgraphs__prior_to_current(M0.dg,M1.dg,\
            is_dsg=False,sg2sg_conn_ratios=sg2sg_conn_ratios,prg=prg)
        MX.append(MicroGraph(G))

    mg = MX.pop(0)
    while len(MX) > 0: 
        mg = mg + MX.pop(0) 
    return mg.dg 

def fetch_source2target_paths(G,sources,targets,prg): 

    st_path_map = dict() 
    for source in sources: 
        bdfs2 = BDFSCache(source,G,is_bfs=False,prg=prg,\
        edge_cost_function=lambda u,v:1,num_paths_per_node=1,max_search_radius=float('inf'),\
        verbose=False)

        while bdfs2.move_one(): continue 

        st_path_map[source] = dict() 
        for t in targets: 
            q = bdfs2.min_paths[t][0]
            st_path_map[source][t] = q 
    return st_path_map

def generate_m_square_integer_matrixes(m,n,prg,ranged_modulo): 
    prg_ = prg__single_to_nvec(prg,n) 

    def one_square_matrix(): 
        x = np.zeros((n,n)) 
        for i in range(n): 
            x[i] = modulo_in_range(prg_(),ranged_modulo) 
        return x 

    matrixes = [] 
    for _ in range(m): 
        matrixes.append(one_square_matrix()) 
    return matrixes 

def max_number_of_relays_per_target(number_of_sources,relays_per_source=2):  
    s = ceil(number_of_sources) 
    return s * relays_per_source

"""
data structure used for simulation Poison Trace Bot. 
"""
class PoisonDeliveryNetwork: 

    def __init__(self,G:defaultdict,source_map,target_map,verbose:bool=False):  
        assert type(verbose) == bool 
        self.G = G 
        self.source_map = source_map  
        self.target_map = target_map 
        self.verbose = verbose 
        self.relay_map = defaultdict(list) 
        self.pending_poisons = dict() 
        self.set_verbosity() 
        return 

    def set_verbosity(self): 
        for t in self.target_map.values(): 
            t.verbose = self.verbose 

    def set_target_prngs(self,prng_map): 
        for k,v in prng_map.items(): 
            assert k in self.target_map 
            self.target_map[k].set_prng(v) 
        return 

    def target_performances(self,display:bool=True): 
        d = {}  
        x = sorted(self.target_map.keys()) 
        for x_ in x: 
            q = self.target_map[x_] 
            
            x = self.target_perf(x_) 

            if display: 
                print("idn: ",x_) 
                print("number of terminations: ",x[0]) 
                print("number of guesses: ",x[1]) 
                print("number of poisonings: ",x[2])
                print()
            d[x_] = x  
        return d 

    def target_perf(self,t_idn): 
        q = self.target_map[t_idn] 
        return (q.target_idn,q.guess_count,q.poison_count)

    def __next__(self): 
        self.move_sources() 
        self.move_targets() 

    def move_sources(self): 
        self.pending_poisons.clear() 
        sources = sorted(self.source_map.keys())
        for s in sources: 
            self.move_source(s) 
        return

    def move_source(self,source_idn): 
        q = self.source_map[source_idn] 

        if type(q.active_poison_action) == type(None):  
            q.send_poison(self.occupied_targets()) 

        x,mode = next(q)

        # case: poison has finished, terminate target 
        if q.active_poison_action.fin_stat: 
            t_ = q.active_poison_action.path_target() 
            t = self.target_map[t_] 
            self.target_map[t_].terminated = True 

        if type(mode) == type(None): return 

        self.process_source_move(source_idn,x,mode) 
        return

    def process_source_move(self,source_idn,x,mode): 
        pp = self.source_map[source_idn].active_poison_action 

        if self.verbose: 
            print("source: ",source_idn) 
            print("mode: ",mode)
            print("info:\n",x) 
            print(pp)
            print("----------------")

        if mode == "send": 
            possible_candidates = set(self.source_map.keys()) 
            for t in self.target_map.values(): 
                t.relay_register(pp,possible_candidates) 
            return 
        # case: pending receive for target  
        t = pp.path_target()
        assert t not in self.pending_poisons 
        self.pending_poisons[t] = (x,pp.poison_type)  
        return

    def move_targets(self): 
        targets = sorted(self.target_map.keys()) 

        for t in targets:
            self.move_target(t) 
        return

    def move_target(self,target_idn):
        t = self.target_map[target_idn] 
        pstat = t.is_poisoned() 

        if self.verbose and pstat: 
            print("target {}, terminated? {}".format(target_idn,t.terminated))
            print("target DB size: {}".format(len(t.poison_db))) 
        finished_target = next(t) 

        if self.verbose and pstat:  
            print("is poisoned: {}".format(pstat)) 

        if finished_target: 
            if self.verbose: 
                print("reproducing terminated agent {}".format(target_idn)) 
            
            s = self.poison_source_of_target(target_idn)
            s.clear_poison_action() 
            self.target_map[target_idn] = t.reproduce()
            if self.verbose: print("--------------------------------------") 
            return 

        # case: target has been poisoned 
        if pstat and target_idn in self.pending_poisons: 
            pred = t.predict_poison()
            x = self.pending_poisons[target_idn][0]

            if self.verbose:
                print("-- reaction {}".format(len(t.poison_reaction_log))) 
                print("actual: ",x) 
                print("predicted: ",pred) 

            # compare prediction with actual 
            #   subcase: correct prediction, halt poison 
            if type(pred) != type(None): 
                if equal_iterables(x,pred,5): 
                    if self.verbose: print("-- halting poison.") 
                    self.halt_poison(target_idn)  
            #   subcase: start backtracking if no guesses 
            else:
                if type(t.backtracker) == type(None):
                    if self.verbose: print("-- starting backtracker")             
                    s = self.poison_source_of_target(target_idn) 
                    assert type(s) != type(None) 
                    pp = s.active_poison_action
                    source_info = deepcopy(s.poison_prng_map[pp.poison_idn()]) 
                    t.start_backtrack(pp,source_info) 


        if target_idn in self.pending_poisons: 
            x = self.pending_poisons[target_idn]
            if len(t.poison_reaction_log) == 0: 
                x2 = x[0] 
            else: 
                x2 = None if x[1] == "inexpressive" else x[0] 

            t.register_poison_reaction(x2) 
            del self.pending_poisons[target_idn] 

        if self.verbose and pstat: print("--------------------------------------") 

        ## 
        return 

    def occupied_targets(self): 
        targets = set() 
        for s in self.source_map.values(): 
            if type(s.active_poison_action) == type(None): continue 
            targets |= {s.active_poison_action.path_target()}
        return targets 

    def poison_source_of_target(self,target_idn): 
        for s in self.source_map.values(): 
            if type(s.active_poison_action) == type(None): 
                continue 

            if s.active_poison_action.path_target() == target_idn: 
                return s 
        return None 

    def halt_poison(self,t_idn): 
        t = self.target_map[t_idn]
        t.reset() 

        s = self.poison_source_of_target(t_idn) 
        s.clear_poison_action() 

        if t_idn in self.pending_poisons: 
            del self.pending_poisons[t_idn]
        return

    @staticmethod 
    def generate_instance(num_source_nodes,num_targets,num_poisons,poison2source_ratio_range,poison_matrix_square_dim,\
        expressive_mode,prg,relays_per_source=2,relay_accuracy_range=[0.75,0.9],verbose:bool=False):  

        assert num_source_nodes <= num_targets 
        # generate the base graph 
        source_nodes = set([i for i in range(num_source_nodes)]) 
        T = TreeGen.generate_tree__mroot_n_leaves(source_nodes,num_targets,prg,is_dsg=False,\
            growth_type="ordered",branching_range=[1,2]) 
        G = connect_TreeGen_forest(T,prg) 
        L = T.leaves 

        # generate the poisons 
        poison_matrices = generate_m_square_integer_matrixes(num_poisons,poison_matrix_square_dim,prg,DEFAULT_POISON_MODEL_SNT_MINMAX)
        poison_matrix_map = {i:m for (i,m) in enumerate(poison_matrices)} 

        # calculate the paths of every source to targets 
        source2target_path_map = fetch_source2target_paths(G,source_nodes,L,prg)

        # generate 1 PRNG per source 
        prgs = prg_to_prg__LCG_sequence(prg,num_source_nodes,moduli_scale=2.7799)

        # generate the sources 
        psources = dict() 
        for i in range(num_source_nodes):
            target_path_map = source2target_path_map[i]  
            prgx = prgs[i]

            if poison2source_ratio_range[0] == poison2source_ratio_range[1]: 
                r = poison2source_ratio_range[0] 
            else: 
                r = modulo_in_range(prg(),poison2source_ratio_range)

            m_indices = sorted(poison_matrix_map)
            psize = ceil(num_poisons * r)
            m_indices = prg_choose_n(m_indices,psize,prg__single_to_int(prg),is_unique_picker=True) 

            poison_matrix_map_ = {j:poison_matrix_map[j] for j in m_indices}
            psource = PoisonSource(i,target_path_map,poison_matrix_map_,expressive_mode,prgx)
            psources[i] = psource 

        # generate the targets 
        prgs = prg_to_prg__LCG_sequence(prg,num_targets,moduli_scale=3.1122)
        targets = dict() 
        max_relays = max_number_of_relays_per_target(num_source_nodes,relays_per_source)
        for (i,l) in enumerate(L): 
            targets[l] = PoisonTarget(l,0,prgs[i],max_relays,num_source_nodes,\
                relay_accuracy_range)

        return PoisonDeliveryNetwork(G,psources,targets,verbose) 