from graph_models.micrograph import * 
from graph_models.tree_gen import * 
from .poison_snt import * 

"""
for a forest generated by a <TreeGen> instance, connects 
all the forests components. Uses measure 
    (ratio of prior subgraph nodes, ratio of possible edges to current subgraph) 
"""
def connect_TreeGen_forest(T:TreeGen,sg2sg_conn_ratios=(0.3,0.2)): 
    gd = GraphComponentDecomposition(T.d)
    gd.decompose() 

    M = MicroGraph(T.d) 

    c0,c1 = gd.components[0],gd.components[1]
    M0,M1 = M.subgraph_by_nodeset_(c0),M.subgraph_by_nodeset_(c1) 

    MX = [] 
    for i in range(len(gd.components) - 1): 
        c0,c1 = gd.components[i],gd.components[i+1] 
        M0,M1 = M.subgraph_by_nodeset_(c0),M.subgraph_by_nodeset_(c1) 

        G = connect_subgraphs__prior_to_current(M0.dg,M1.dg,\
            is_dsg=False,sg2sg_conn_ratios=sg2sg_conn_ratios,prg=prg)
        MX.append(MicroGraph(G))

    mg = MX.pop(0)
    while len(MX) > 0: 
        mg = mg + MX.pop(0) 
    return mg.dg 

class PoisonDeliveryNetwork: 

    def __init__(self,G:defaultdict,source_nodes,source2target_path_map,poison2source_map,poison_map): 
        self.G = G 
        self.source_nodes = source_nodes  
        self.poison2source_map = poison2source_map 
        self.poison_map = poison_map
        return 

    @staticmethod 
    def generate_instance(num_source_nodes,num_targets,num_poisons,poison2source_variance):  
        return -1