from graph_models.micrograph import * 
from graph_models.tree_gen import * 
from .poison_snt import * 
from morebs2.numerical_generator import prg__single_to_nvec


"""
for a forest generated by a <TreeGen> instance, connects 
all the forests components. Uses measure 
    (ratio of prior subgraph nodes, ratio of possible edges to current subgraph) 
"""
def connect_TreeGen_forest(T:TreeGen,sg2sg_conn_ratios=(0.15,0.1)): 
    gd = GraphComponentDecomposition(T.d)
    gd.decompose() 

    M = MicroGraph(T.d) 

    c0,c1 = gd.components[0],gd.components[1]
    M0,M1 = M.subgraph_by_nodeset_(c0),M.subgraph_by_nodeset_(c1) 

    MX = [] 
    for i in range(len(gd.components) - 1): 
        c0,c1 = gd.components[i],gd.components[i+1] 
        M0,M1 = M.subgraph_by_nodeset_(c0),M.subgraph_by_nodeset_(c1) 

        G = connect_subgraphs__prior_to_current(M0.dg,M1.dg,\
            is_dsg=False,sg2sg_conn_ratios=sg2sg_conn_ratios,prg=prg)
        MX.append(MicroGraph(G))

    mg = MX.pop(0)
    while len(MX) > 0: 
        mg = mg + MX.pop(0) 
    return mg.dg 

def fetch_source2target_paths(G,sources,targets,prg): 

    st_path_map = dict() 
    for source in sources: 
        bdfs2 = BDFSCache(source,G,is_bfs=False,prg=prg,\
        edge_cost_function=lambda u,v:1,num_paths_per_node=1,max_search_radius=float('inf'),\
        verbose=False)

        while bdfs2.move_one(): continue 

        st_path_map[source] = dict() 
        for t in targets: 
            q = bdfs2.min_paths[t][0]
            st_path_map[source][t] = q 
    return st_path_map

def generate_m_square_integer_matrixes(m,n,prg): 
    prg_ = prg__single_to_nvec(prg__single_to_int(prg)) 

    def one_square_matrix(): 
        x = np.zeros((n,n)) 
        for i in range(n): 
            x[i] = prg_() 
        return x 

    matrixes = [] 
    for _ in range(m): 
        matrixes.append(one_square_matrix()) 
    return matrixes 

def max_number_of_relays_per_target(number_of_sources,relays_per_source=2):  
    s = ceil(number_of_sources) 
    return s * relays_per_source

class PoisonDeliveryNetwork: 

    def __init__(self,G:defaultdict,source_map,target_map):  
        self.G = G 
        self.source_map = source_map  
        self.target_map = target_map 
        return 

    @staticmethod 
    def generate_instance(num_source_nodes,num_targets,num_poisons,poison2source_ratio_range,poison_matrix_square_dim,\
        expressive_mode,prg):  
        # generate the base graph 
        source_nodes = set([i for i in range(num_source_nodes)]) 
        T = TreeGen.generate_tree__mroot_n_leaves(source_nodes,num_targets,prg,is_dsg=False,\
            growth_type="ordered",branching_range=[1,2]) 
        G = connect_TreeGen_forest(T)
        L = T.leaves 

        # generate the poisons 
        poison_matrices = generate_m_square_integer_matrixes(num_poisons,poison_matrix_square_dim,prg)
        poison_matrix_map = {i:m for (i,m) in enumerate(poison_matrices)} 

        # calculate the paths of every source to targets 
        source2target_path_map = fetch_source2target_paths(G,source_nodes,L,prg)

        # generate 1 PRNG per source 
        prgs = prg_to_prg__LCG_sequence(prg,num_source_nodes,moduli_scale=2.7799)

        # generate the sources 
        psources = dict() 
        for i in range(num_source_nodes):
            target_path_map = source2target_path_map[i]  
            prgx = prgs[i]

            if poison2source_ratio_range[0] == poison2source_ratio_range[1]: 
                r = poison2source_ratio_range[0] 
            else: 
                r = modulo_in_range(prg(),poison2source_ratio_range)

            m_indices = sorted(poison_matrix_map)
            psize = ceil(num_poisons * r)
            m_indices = prg_choose_n(m_indices,psize,prg__single_to_int(prg),is_unique_picker=True) 

            poison_matrix_map_ = {j:poison_matrix_map[j] for j in m_indices}
            psource = PoisonSource(i,target_path_map,poison_matrix_map_,expressive_mode,prgx)
            psources[i] = psource 

        # generate the targets 
        prgs = prg_to_prg__LCG_sequence(prg,num_targets,moduli_scale=3.1122)
        targets = dict() 
        for (i,l) in enumerate(L): 
            targets[l] = PoisonTarget(l,0,prgs[i])

        return PoisonDeliveryNetwork(G,psources,targets) 