from .graph_introspector import * 
from graph_models.reactive_simple_graph_rules import * 

"""
A subclass of the class<GraphIntrospectorTypeCNO>. 

Uses a <RealtimeReactiveGraphRuleOperatorTypeS> to add or delete nodes and edges. 
For details, see the code for this rule operator. 

In general, graph traversal process, from node n0 to node n1 via edge e0, produces 
changes on the graph of traversal G. The rule R1 for n1 applies its node+edge delta 
onto G. The rule R0 for edge e0 applies changes to G, likewise. 

There is a rule for every node or edge traveled during the traversal process. This 
specification implies G is subject to undergo non-zero changes at every point of 
travel. Every rule R for graph element q is periodic in activation. The period of 
the rule determines when the changes apply. If period is positive integer x, then 
traversal process must encounter graph element q a periodic number of x times before 
rule activates. If <RealtimeReactiveGraphRuleOperatorTypeS.is_rule_constant> is set 
to False, a rule that is activated is replaced by another rule generated by the 
operator. 

NOTE: due to the mutable property of the graph of traversal, edge cost function is 
      assigned to the default (unit 1 distance), so that computing requirements are 
      reduced. 

NOTE: due to slow runtime for calculating components on directed graphs, advise to 
    not employ this class on directed graphs. 
""" 
class ReactiveGraphIntrospectorTypeCNO(GraphIntrospectorTypeCNO):

    def __init__(self,G,edge_cost_function,is_bfs,node2cyclical_outputter,\
        node_priority_function,rule_op,prg,verbose=False):  

        super().__init__(G,edge_cost_function,is_bfs,node2cyclical_outputter,\
            node_priority_function,prg) 

        assert type(rule_op) == RealtimeReactiveGraphRuleOperatorTypeS
        self.rule_op = rule_op 
        self.verbose = verbose 
        return

    def set_prg(self,prg): 
        assert type(prg) in {MethodType,FunctionType}
        
        super().set_prg(prg) 
        self.rule_op.prg = prg 

    """
    main method #1 

    return:
    [0] dict, node -> cyclical value 
    [1] reference node used to travel to next neighbors 
    [1] traversal cost for this timestamp 
    """
    def __next__(self): 
        assert type(self.introspector) != type(None)

        if self.introspector.fin_stat:
            return dict(),None,0 

        # traverse one and log 
        ref = self.introspector.reference 

        assert self.introspector.d == self.G 
        q = self.introspector.move_one()
        M,traversal_cost = self.log_one_traversal()

        # case: traversal process is still active 
        if not self.introspector.fin_stat: 
            self.exec_reaction() 

        self.cumulative_traversal_cost += traversal_cost 

        return M,ref,traversal_cost

    def exec_reaction(self): 
        edges = self.introspector.previous_edges
        self.rule_op.react(self.G,edges,self.verbose) 
        # ineff.
        self.rule_op.clean_up_rules(self.G) 


    @staticmethod
    def generate_instance(G,nodechange_range,edgechange_range,period_range,maintain_connectivity:bool,\
        is_rule_constant:bool,   node_weight_range,is_dsg,is_bfs,ascending_priority,cycle_length_range,prg,verbose=False):  

        edge_cost_function = DEFAULT_EDGE_COST_FUNCTION 

        prg_ = prg__single_to_int(prg)
        node2cyclical_outputter = CumulativeNode2Cycle.generate_instance(set(G.keys()),cycle_length_range,prg_)

        node_priority_outputter = NodePriorityFunctionStruct.generate_instance(\
            G,node_weight_range,is_dsg,is_bfs,ascending_priority,prg)

        N = set(G.keys()) 
        rule_op = RealtimeReactiveGraphRuleOperatorTypeS(N,is_dsg,nodechange_range,\
            edgechange_range,period_range,maintain_connectivity,is_rule_constant,prg) 

        return ReactiveGraphIntrospectorTypeCNO(G,edge_cost_function,is_bfs,\
            node2cyclical_outputter,node_priority_outputter,rule_op,prg,verbose) 