# NOTE: code in this file was generated by an AI LLM. 
# all lines ending with #$ was AI-generated. 

import streamlit as st #$
import networkx as nx #$
import matplotlib.pyplot as plt #$
import re #$

# ── Ultra-clean page (no headers, no scroll) ──
st.set_page_config(layout="wide", page_title="Graph") #$
hide_style = """
<style>
    #MainMenu, header, footer {visibility: hidden;}
    .css-1d391kg {padding: 0 !important; margin: 0 !important;}
    .block-container {padding-top: 0 !important; padding-bottom: 0 !important;}
    section[data-testid="stSidebar"] {top: 0; height: 100vh;}
</style>
""" #$
st.markdown(hide_style, unsafe_allow_html=True) #$

# ── Full graph ── #$
G = nx.complete_graph(4) #$
pos = nx.spring_layout(G, seed=42) #$

# ── Sidebar input (thin & fixed) ── #$
with st.sidebar: #$
    st.write("**Nodes (CSV)**") #$
    txt = st.text_input("e.g. 0, 2, 3", value="0", label_visibility="collapsed") #$
    if st.button("Show", use_container_width=True): #$
        pass  # Trigger rerun #$

# ── Parse nodes ── #$
try: #$
    selected = [int(x) for x in re.split(r'[,;\s]+', txt.strip()) if x.isdigit()] #$
    selected = [n for n in selected if 0 <= n <= 3] or [0] #$
    selected = list(dict.fromkeys(selected))  # preserve order, remove dupes #$
except: #$
    selected = [0] #$

# ── Edges between selected nodes only ── #$
edges = [(u,v) for u,v in G.edges() if u in selected and v in selected] #$

# ── Create figure that fills the top area ── #$
fig = plt.figure(figsize=(14, 9), dpi=100) #$
ax = fig.add_subplot(111) #$

# Inactive nodes (very faint) #$
nx.draw_networkx_nodes(G, pos, #$
                       nodelist=[n for n in G if n not in selected], #$
                       node_color="#e0e0e0", node_size=800, alpha=0.4, ax=ax) #$

# Active nodes (vibrant) #$
nx.draw_networkx_nodes(G, pos, #$
                       nodelist=selected, #$
                       node_color="#1f77b4", node_size=1300, #$
                       edgecolors="white", linewidths=5, ax=ax) #$

# Strong edges between selected #$
nx.draw_networkx_edges(G, pos, edgelist=edges, #$
                       edge_color="#1f77b4", width=5, alpha=0.9, ax=ax) #$

# Very faint possible edges #$
nx.draw_networkx_edges(G, pos, #$
                       edgelist=[e for e in G.edges() if e not in edges], #$
                       edge_color="#bbbbbb", width=1, alpha=0.2, style="dashed", ax=ax) #$

# Labels #$
nx.draw_networkx_labels(G, pos, font_size=22, font_weight="bold", ax=ax) #$

ax.axis("off") #$
plt.subplots_adjust(left=0, right=1, top=1, bottom=0) #$
plt.margins(0.15) #$

# ── Display at the very top, no scroll ── #$
st.pyplot(fig, use_container_width=True) #$
plt.close(fig) #$

# Optional tiny footer (won't cause scroll) #$
st.caption(f"Selected: {', '.join(map(str, selected)) or 'none'}") #$